### ISSUE TITLE
Wrong time displayed for cet region

### ISSUE THREAD

**Issue by PfurtschellerP** [hartator/wheniskeynote.com#21]
The time calculation seems to not take into account the time change to winter time.
![image](https://user-images.githubusercontent.com/57419021/98676635-25054d80-235c-11eb-82f2-f1db42e47a1a.png)
![image](https://user-images.githubusercontent.com/57419021/98676750-4b2aed80-235c-11eb-82e4-e9b5fb2ff16b.png)

**Comment by PfurtschellerP** [comment]
Just saw that raphaklr already supplied a patch. Must only be merged. #19

**Comment by nikolak** [comment]
The time is still wrong for the Europe time zone.

The WWDC 2022 time is 10AM PST which is 7PM CEST, however the time displayed on the website is 8PM local time.

To make matters worse the calendar link would also create an entry for 8PM instead of letting the phone do the localization itself.
